#!/usr/bin/env python3
"""Extract a schema-only baseline from a phpMyAdmin SQL dump.

This script never connects to MySQL. It consumes a dump file on disk and
writes a deterministic, data-free baseline that can be applied to an empty
database.

Every transformation below is deliberate and documented in
``migrations/MIGRATION_VERSIONING.md``:

* ``INSERT INTO`` blocks are dropped, so no production rows, customer data
  or password hashes ever reach the repository.
* ``START TRANSACTION`` / ``COMMIT`` are dropped. The migration runner owns
  transaction boundaries; a stray ``COMMIT`` inside the file would silently
  close the runner's transaction mid-apply and break rollback on failure.
* ``AUTO_INCREMENT=<n>`` *table options* are stripped so a clean install
  starts numbering at 1 and the file does not leak production row counts.
  The ``AUTO_INCREMENT`` *column attribute* is preserved, because phpMyAdmin
  declares it in a trailing ``ALTER TABLE ... MODIFY`` rather than in
  ``CREATE TABLE``.
* ``DEFINER=`user`@`host``` is removed from views and triggers. Production
  objects are owned by ``farforre_rentalhub``; keeping that clause makes the
  baseline fail with error 1449 on any database whose user differs.
* The phpMyAdmin preamble comments are removed, because they embed the
  production host name and exporter version into a committed file.
* One-off backup tables (``<name>_bk_<date>_<time>``) are excluded. They are
  2026-06-17 snapshots, not part of the application schema.

Statement order from the source dump is preserved verbatim, which keeps
phpMyAdmin's dependency ordering intact: tables, then triggers, then indexes
and auto-increment attributes, then the view, then foreign keys last.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# `fin_payments_bk_20260617_1955`, `orders_discount_bk_20260617_1955`, ...
BACKUP_TABLE_RE = re.compile(r"_bk_\d{8}_\d{4}$")

# Leading object name of a statement, e.g. CREATE TABLE `orders` (
STATEMENT_TARGET_RE = re.compile(
    r"^(?:CREATE\s+TABLE|ALTER\s+TABLE|INSERT\s+INTO|REPLACE\s+INTO|"
    r"DROP\s+TABLE(?:\s+IF\s+EXISTS)?|TRUNCATE\s+TABLE|LOCK\s+TABLES)\s+`([^`]+)`",
    re.IGNORECASE,
)

# `ON `fin_payments` FOR EACH ROW` inside a CREATE TRIGGER block.
TRIGGER_TARGET_RE = re.compile(r"\bON\s+`([^`]+)`", re.IGNORECASE)

DEFINER_RE = re.compile(r"\s*DEFINER=`[^`]*`@`[^`]*`")

# Table option only: requires `=<digits>`, so the column attribute survives.
AUTO_INCREMENT_OPTION_RE = re.compile(r",?\s*AUTO_INCREMENT=\d+")

DATA_STATEMENT_PREFIXES = ("INSERT INTO", "REPLACE INTO", "LOCK TABLES", "UNLOCK TABLES")

TRANSACTION_STATEMENT_PREFIXES = ("START TRANSACTION", "COMMIT", "ROLLBACK", "BEGIN;")

# phpMyAdmin preamble: leaks production host and tooling versions.
HEADER_COMMENT_RE = re.compile(
    r"^--\s*(?:phpMyAdmin SQL Dump|version\s|https://www\.phpmyadmin\.net"
    r"|Хост:|Час створення:|Версія сервера:|Версія PHP:"
    r"|Host:|Generation Time:|Server version:|PHP Version:"
    r"|База даних:|Database:)",
)

BANNER = """-- ---------------------------------------------------------------------------
-- 000_baseline.sql - schema-only baseline of the RentalHub production database
--
-- Generated by backend/scripts/extract_baseline.py from a phpMyAdmin dump.
-- DO NOT EDIT BY HAND: regenerate from a fresh dump instead.
--
-- Contains structure only: no rows, no AUTO_INCREMENT counters, no DEFINER
-- clauses, no transaction control, no one-off `*_bk_<date>_<time>` tables.
--
-- This file is the starting point for a clean install. It must NEVER be
-- applied to a database that already contains the schema; see
-- migrations/MIGRATION_VERSIONING.md for the EMPTY / LEGACY_UNTRACKED /
-- TRACKED state rules.
-- ---------------------------------------------------------------------------
"""


class BaselineExtractor:
    """Line-oriented filter over a phpMyAdmin dump."""

    def __init__(self) -> None:
        self.output: list[str] = []
        self.pending: list[str] = []
        self.dropped_inserts = 0
        self.dropped_transactions = 0
        self.dropped_header_comments = 0
        self.excluded_tables: set[str] = set()
        self.excluded_triggers: set[str] = set()

    # -- emission helpers -------------------------------------------------
    def _flush_pending(self) -> None:
        for line in self.pending:
            if HEADER_COMMENT_RE.match(line.strip()):
                self.dropped_header_comments += 1
                continue
            self.output.append(line)
        self.pending.clear()

    def _discard_pending(self) -> None:
        self.pending.clear()

    def _emit(self, text: str) -> None:
        text = DEFINER_RE.sub("", text)
        text = AUTO_INCREMENT_OPTION_RE.sub("", text)
        self._flush_pending()
        self.output.append(text)

    # -- statement handling ----------------------------------------------
    def handle_statement(self, lines: list[str]) -> None:
        text = "".join(lines)
        head = text.lstrip()
        upper = head[:64].upper()

        if upper.startswith(DATA_STATEMENT_PREFIXES):
            self.dropped_inserts += 1
            self._discard_pending()
            return

        if upper.startswith(TRANSACTION_STATEMENT_PREFIXES):
            self.dropped_transactions += 1
            self._discard_pending()
            return

        match = STATEMENT_TARGET_RE.match(head)
        if match and BACKUP_TABLE_RE.search(match.group(1)):
            self.excluded_tables.add(match.group(1))
            self._discard_pending()
            return

        self._emit(text)

    def handle_trigger_block(self, lines: list[str]) -> None:
        text = "".join(lines)
        match = TRIGGER_TARGET_RE.search(text)
        if match and BACKUP_TABLE_RE.search(match.group(1)):
            self.excluded_triggers.add(match.group(1))
            self._discard_pending()
            return
        self._emit(text)

    # -- main loop --------------------------------------------------------
    def run(self, dump_path: Path) -> None:
        statement: list[str] = []
        trigger_block: list[str] = []
        in_trigger = False

        with dump_path.open("r", encoding="utf-8", errors="replace") as handle:
            for raw in handle:
                stripped = raw.strip()

                if in_trigger:
                    trigger_block.append(raw)
                    if stripped.upper() == "DELIMITER ;":
                        self.handle_trigger_block(trigger_block)
                        trigger_block = []
                        in_trigger = False
                    continue

                if not statement and stripped.upper().startswith("DELIMITER $$"):
                    in_trigger = True
                    trigger_block = [raw]
                    continue

                if not statement and (stripped.startswith("--") or not stripped):
                    self.pending.append(raw)
                    continue

                statement.append(raw)
                if stripped.endswith(";"):
                    self.handle_statement(statement)
                    statement = []

        if statement:  # unterminated tail: keep it rather than silently lose it
            self.handle_statement(statement)
        if trigger_block:
            self.handle_trigger_block(trigger_block)


def summarise(text: str) -> dict[str, int]:
    """Count objects in the produced baseline for the console report."""
    return {
        "create_table": len(re.findall(r"^CREATE TABLE ", text, re.MULTILINE)),
        "create_view": len(re.findall(r"\bCREATE\b[^;\n]*\bVIEW\b", text)),
        "create_trigger": len(re.findall(r"\bCREATE TRIGGER\b", text)),
        "alter_table": len(re.findall(r"^ALTER TABLE ", text, re.MULTILINE)),
        "primary_key": len(re.findall(r"\bADD PRIMARY KEY\b", text)),
        "unique_key": len(re.findall(r"\bADD UNIQUE KEY\b", text)),
        "plain_key": len(re.findall(r"\bADD KEY\b", text)),
        "foreign_key": len(re.findall(r"\bADD CONSTRAINT\b", text)),
        "leftover_inserts": len(re.findall(r"^INSERT INTO ", text, re.MULTILINE)),
        "leftover_definer": len(re.findall(r"\bDEFINER=", text)),
        "leftover_backup": len(re.findall(r"_bk_\d{8}_\d{4}", text)),
        "leftover_commit": len(re.findall(r"^(?:COMMIT|START TRANSACTION)", text, re.MULTILINE)),
        "leftover_host": len(re.findall(r"ukraine\.com\.ua|phpMyAdmin", text)),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dump", required=True, help="path to the phpMyAdmin dump")
    parser.add_argument("--out", required=True, help="path of the baseline to write")
    args = parser.parse_args()

    dump_path = Path(args.dump)
    if not dump_path.is_file():
        print(f"ERROR: dump not found: {dump_path}", file=sys.stderr)
        return 2

    extractor = BaselineExtractor()
    extractor.run(dump_path)

    body = "".join(extractor.output).rstrip() + "\n"
    text = BANNER + "\n" + body

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")

    # Scan the extracted body only. The banner legitimately mentions the
    # exporter name, and including it here would flag our own header.
    stats = summarise(body)
    print(f"source dump : {dump_path} ({dump_path.stat().st_size:,} bytes)")
    print(f"baseline    : {out_path} ({out_path.stat().st_size:,} bytes)")
    print(f"data blocks dropped     : {extractor.dropped_inserts}")
    print(f"txn statements dropped  : {extractor.dropped_transactions}")
    print(f"header comments dropped : {extractor.dropped_header_comments}")
    print(f"backup tables excluded  : {len(extractor.excluded_tables)}")
    for name in sorted(extractor.excluded_tables):
        print(f"    - {name}")
    print("--- objects in baseline ---")
    print(f"CREATE TABLE      : {stats['create_table']}")
    print(f"CREATE VIEW       : {stats['create_view']}")
    print(f"CREATE TRIGGER    : {stats['create_trigger']}")
    print(f"ALTER TABLE       : {stats['alter_table']}")
    print(f"PRIMARY KEY       : {stats['primary_key']}")
    print(f"UNIQUE KEY        : {stats['unique_key']}")
    print(f"KEY (index)       : {stats['plain_key']}")
    print(f"FOREIGN KEY       : {stats['foreign_key']}")
    print("--- safety checks (all must be 0) ---")
    print(f"leftover INSERT   : {stats['leftover_inserts']}")
    print(f"leftover DEFINER  : {stats['leftover_definer']}")
    print(f"leftover *_bk_*   : {stats['leftover_backup']}")
    print(f"leftover COMMIT   : {stats['leftover_commit']}")
    print(f"leftover host/tool: {stats['leftover_host']}")

    checks = (
        "leftover_inserts",
        "leftover_definer",
        "leftover_backup",
        "leftover_commit",
        "leftover_host",
    )
    failures = [key for key in checks if stats[key]]
    if failures:
        print(f"ERROR: safety checks failed: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())